services:
    servidor_web:
        image: nginx:latest
        container_name: nginx_standalone
        volumes:
            - ./html:/var/www/html
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8777:80
        restart: always